version: '3.8'
services:
  vprodb:
    build: ./Docker-files/db
    image: mitul006/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata: /var/lib/mysql
    enviroment: 
      - MYSQL_ROOT_PASSWORD=mysql  

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01: 
    image: rabbitmq
    port: 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      
  vproapp:
    build: ./Docker-files/app
    image: mitul006/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata: /usr/local/tomcat/webapp

  vproweb:
    build: ./Docker-files/web
    image: mitul006/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
volumes:
  - vprodbdata: {}
  - vproappdata: {} 
   



